<template>
  <div class="xfn-order-list">
    <el-breadcrumb>
      <el-breadcrumb-item to="/main">首页</el-breadcrumb-item>
      <el-breadcrumb-item>订单详情</el-breadcrumb-item>
    </el-breadcrumb>
    <br>
    <el-table
    :data="tableData"
    border
    style="width: 100%">
    <el-table-column
      prop="orderid"
      label="订单编号"
      width="180">
    </el-table-column>
    <el-table-column
      prop="startTime"
      label="开始时间"
      width="180">
    </el-table-column>
    <el-table-column
      prop="endTime"
      label="结束时间">
    </el-table-column>
    <el-table-column
      prop="cuscount"
      label="用餐人数">
    </el-table-column>
    <el-table-column
      prop="table"
      label="桌台编号">
    </el-table-column>
    <el-table-column
      prop="dishdetail"
      label="菜品详情">
    </el-table-column>
  </el-table>
  </div>
</template>
